version: "3.9"
services:
  lets-do-it:
    image: postgres
    restart: always
    container_name: letsdoit
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
